# Generated by Django 2.2.12 on 2020-04-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200405_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Blogs',
        ),
    ]
